# Configuration

config:

  line_length:
    line_length: 120
    code_blocks: false
    tables: false
  html:
    allowed_elements:
      - div
  no-duplicate-heading: false

# Globs

globs:

- "**/*.md"
- "*.md"

# Ignores

ignores:

- "site/**/*.md"
- ".github/**/*.md"
- "renv/**/*.md"

# Fix any fixable errors

fix: true
